/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'
import { Route as GuidesMeilleursParfumsOccasionsRouteImport } from './routes/guides.meilleurs-parfums-occasions'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesMeilleursParfumsOccasionsRoute =
  GuidesMeilleursParfumsOccasionsRouteImport.update({
    id: '/guides/meilleurs-parfums-occasions',
    path: '/guides/meilleurs-parfums-occasions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/livraison': typeof LivraisonRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/meilleurs-parfums-occasions': typeof GuidesMeilleursParfumsOccasionsRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/livraison': typeof LivraisonRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/meilleurs-parfums-occasions': typeof GuidesMeilleursParfumsOccasionsRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/boutique': typeof BoutiqueRoute
  '/contact': typeof ContactRoute
  '/livraison': typeof LivraisonRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/meilleurs-parfums-occasions': typeof GuidesMeilleursParfumsOccasionsRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/livraison'
    | '/panier'
    | '/sitemap.xml'
    | '/guides/meilleurs-parfums-occasions'
    | '/produit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/livraison'
    | '/panier'
    | '/sitemap.xml'
    | '/guides/meilleurs-parfums-occasions'
    | '/produit/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/boutique'
    | '/contact'
    | '/livraison'
    | '/panier'
    | '/sitemap.xml'
    | '/guides/meilleurs-parfums-occasions'
    | '/produit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BoutiqueRoute: typeof BoutiqueRoute
  ContactRoute: typeof ContactRoute
  LivraisonRoute: typeof LivraisonRoute
  PanierRoute: typeof PanierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesMeilleursParfumsOccasionsRoute: typeof GuidesMeilleursParfumsOccasionsRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/meilleurs-parfums-occasions': {
      id: '/guides/meilleurs-parfums-occasions'
      path: '/guides/meilleurs-parfums-occasions'
      fullPath: '/guides/meilleurs-parfums-occasions'
      preLoaderRoute: typeof GuidesMeilleursParfumsOccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BoutiqueRoute: BoutiqueRoute,
  ContactRoute: ContactRoute,
  LivraisonRoute: LivraisonRoute,
  PanierRoute: PanierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesMeilleursParfumsOccasionsRoute: GuidesMeilleursParfumsOccasionsRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
